### ISSUE TITLE
fully automated autoinstall shows a blank console

### ISSUE THREAD

**Issue by dbungert** [canonical/ubuntu-desktop-installer#2356]
### What happened?

Give the installer some autoinstall.yaml that does not use interactive-sections.  Instead of the normal journal-based scroll in the console, we get a blank console.

### What was expected?

journal-based scroll similar to what is seen when doing non-autoinstall

### Steps to reproduce

1. Apply autoinstall through a supported method.   https://ubuntu.com/server/docs/install/autoinstall-quickstart has two sample methods for doing so.  Here is a specific sample autoinstall in cloud-config format that reproduces the problem:
```yaml
#cloud-config
autoinstall:
  version: 1
  identity:
    realname: ''
    hostname: ubuntu
    username: ubuntu
    password: '$6$wdAcoXrU039hKYPd$508Qvbe7ObUnxoj15DRCkzC3qO7edjH0VV7BPNRDYK4QR8ofJaEEF2heacn0QgD.f8pO8SNp83XNdWG6tocBM1'
```
2. Allow install to proceed.
3. Press console button in bottom-right

### Additional context

![image](https://github.com/canonical/ubuntu-desktop-installer/assets/235157/2fb75725-1364-4bb2-bb3c-0842caf9c174)
