### ISSUE TITLE
autoinstall late-commands always fail

### ISSUE THREAD

**Issue by jamesps-ebi** [canonical/ubuntu-desktop-installer#2401]
### What happened?

When installing a system using the Desktop ISO (e.g. 23.10.1 Mantic Desktop ISO) and using an autoinstall, any late-commands that are run within the target system (curtin in-target -- ) is generating the errors.

### What was expected?

Commands in the late-commands section should run without failing.

The same commands run on a server ISO install do not produce errors.

### Steps to reproduce

- Generate a simple autoinstall yaml
```
autoinstall:
  version: 1
  interactive-sections:
    - keyboard
    - network
  locale: en_GB.UTF-8
  keyboard:
    layout: gb
  kernel:
    flavor: hwe
  identity:
    hostname: unassigned-hostname
    username: test123
    realname: Test User
    password: 'pwd_hash_here'
  storage:
    grub:
      reorder_uefi: false
    layout:
      name: lvm
  user-data:
    timezone: Europe/London
  late-commands:
    - curtin in-target --target=/target -- echo testing123 > /etc/hostname
```
- Download and run 23.10.1 desktop installer with the autoinstall yaml
- Wait for install to complete and you will see an error pop up. From the logs, you can see the late-commands will have failed.
