### ISSUE TITLE
[autoinstall] missing packages on the live image: mdadm, multipath-tools

### ISSUE THREAD

**Issue by paride** [canonical/ubuntu-desktop-installer#613]
When trying to perform an autoinstall (currently booting with `experimental-autoinstall` in the cmdline) with the canary images with a simple `user-data` like:
```
#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    username: ubuntu
```
the installer fails looking for binaries from the `mdadm` and `multipath-tools` packages. I think subiquity assumes they're present because they're part of the server ISO images. For feature parity they should be included in the Desktop images too.

As a workaround adding this to the `user-data` makes subiquity not call the missing tools:

```
  storage:
    layout:
      name: direct
```

Cc: @mwhudson as I think this is your domain :-)
