### ISSUE TITLE
[autoinstall] subiquity assumes the live system netplan uses systemd-networkd

### ISSUE THREAD

**Issue by paride** [canonical/ubuntu-desktop-installer#614]
When trying to perform an autoinstall (currently booting with `experimental-autoinstall` in the cmdline) with the canary Desktop images with a simple `user-data` like:
```
#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    username: ubuntu
```
subiquity fails configuring the network on the live system. It drops some configuration to `/etc/netplan` which assumes the netplan renderer is networkd, but in the Desktop live installer that's NetworkManager. The resulting config is hybrid/wrong, and the installation fails as subiquity tries to `netplan apply`, which fails because `systemd-networkd` is not running (which is expected).

I don't see a trivial way to fix this which doesn't involve adding logic to subiquity to detect the currently used renderer. Given that cloud-init is already able to deal with different renderers, subiquity cloud leverage cloud-init to configure the live system network, instead of adding its own netplan config.

Cc: @blackboxsw
